#!/bin/bash
e

c

h

o

"

B

e

s

t

S

c

h

o

ol"

>

>

"

\

	*

\

	\

	\'\

	"

	B

	e

	s

	t

	S

	c

	h

	o

	ol\

		"

	\'\

		\

		\

		*

		$

		\

			?

		\

			*

		\

			*

		\

			*

		\

			*

		\

			*

		:

	)


